"""add weekly plans and weekly plan items

Revision ID: 05eeb8e1a256
Revises: 93f4e57e7bcf
Create Date: 2026-09-11 20:02:47.388194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '05eeb8e1a256'
down_revision: Union[str, None] = '93f4e57e7bcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_plans',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('teacher_user_id', sa.UUID(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_user_id', 'week_start_date', name='uq_weekly_plan_teacher_week')
    )
    op.create_index(op.f('ix_weekly_plans_organization_id'), 'weekly_plans', ['organization_id'], unique=False)
    op.create_index(op.f('ix_weekly_plans_teacher_user_id'), 'weekly_plans', ['teacher_user_id'], unique=False)
    op.create_table('weekly_plan_items',
    sa.Column('weekly_plan_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('lesson_plan_id', sa.UUID(), nullable=True),
    sa.Column('day_of_week', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='day_of_week'), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('topic_override', sa.String(length=250), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_plan_id'], ['lesson_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['weekly_plan_id'], ['weekly_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_plan_items_class_id'), 'weekly_plan_items', ['class_id'], unique=False)
    op.create_index(op.f('ix_weekly_plan_items_lesson_plan_id'), 'weekly_plan_items', ['lesson_plan_id'], unique=False)
    op.create_index(op.f('ix_weekly_plan_items_weekly_plan_id'), 'weekly_plan_items', ['weekly_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_plan_items_weekly_plan_id'), table_name='weekly_plan_items')
    op.drop_index(op.f('ix_weekly_plan_items_lesson_plan_id'), table_name='weekly_plan_items')
    op.drop_index(op.f('ix_weekly_plan_items_class_id'), table_name='weekly_plan_items')
    op.drop_table('weekly_plan_items')
    op.drop_index(op.f('ix_weekly_plans_teacher_user_id'), table_name='weekly_plans')
    op.drop_index(op.f('ix_weekly_plans_organization_id'), table_name='weekly_plans')
    op.drop_table('weekly_plans')
    # ### end Alembic commands ###
