"""Add lesson plans and versions

Revision ID: 06e9cafed403
Revises: f104d3b834f0
Create Date: 2026-09-13 07:00:50.173547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '06e9cafed403'
down_revision: Union[str, None] = 'f104d3b834f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_plans',
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('year_group_id', sa.UUID(), nullable=False),
    sa.Column('curriculum_topic_id', sa.UUID(), nullable=True),
    sa.Column('topic_title', sa.String(length=300), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('ability_level', sa.Enum('SUPPORT', 'CORE', 'GREATER_DEPTH', 'MIXED', name='ability_level'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_topic_id'], ['curriculum_topics.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['year_group_id'], ['year_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_plans_owner_user_id'), 'lesson_plans', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_lesson_plans_subject_id'), 'lesson_plans', ['subject_id'], unique=False)
    op.create_index(op.f('ix_lesson_plans_year_group_id'), 'lesson_plans', ['year_group_id'], unique=False)
    op.create_table('lesson_plan_versions',
    sa.Column('lesson_plan_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('generation_kind', sa.Enum('FULL_GENERATION', 'SECTION_REGENERATION', 'MANUAL_EDIT', name='lesson_plan_generation_kind'), nullable=False),
    sa.Column('generation_notes', sa.Text(), nullable=True),
    sa.Column('safeguarding_flagged', sa.Boolean(), nullable=False),
    sa.Column('safeguarding_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lesson_plan_id'], ['lesson_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_plan_id', 'version_number', name='uq_lesson_plan_version_number')
    )
    op.create_index(op.f('ix_lesson_plan_versions_lesson_plan_id'), 'lesson_plan_versions', ['lesson_plan_id'], unique=False)
    op.create_table('lesson_plan_version_resources',
    sa.Column('lesson_plan_version_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_plan_version_id'], ['lesson_plan_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_plan_version_id', 'resource_id', name='uq_version_resource')
    )
    op.create_index(op.f('ix_lesson_plan_version_resources_lesson_plan_version_id'), 'lesson_plan_version_resources', ['lesson_plan_version_id'], unique=False)
    op.create_index(op.f('ix_lesson_plan_version_resources_resource_id'), 'lesson_plan_version_resources', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_plan_version_resources_resource_id'), table_name='lesson_plan_version_resources')
    op.drop_index(op.f('ix_lesson_plan_version_resources_lesson_plan_version_id'), table_name='lesson_plan_version_resources')
    op.drop_table('lesson_plan_version_resources')
    op.drop_index(op.f('ix_lesson_plan_versions_lesson_plan_id'), table_name='lesson_plan_versions')
    op.drop_table('lesson_plan_versions')
    op.drop_index(op.f('ix_lesson_plans_year_group_id'), table_name='lesson_plans')
    op.drop_index(op.f('ix_lesson_plans_subject_id'), table_name='lesson_plans')
    op.drop_index(op.f('ix_lesson_plans_owner_user_id'), table_name='lesson_plans')
    op.drop_table('lesson_plans')
    # ### end Alembic commands ###
