"""fix weekly plan uniqueness constraint to include organization_id

Revision ID: 096c5d16eaec
Revises: 8824f0acf3f2
Create Date: 2026-09-11 20:43:56.884313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '096c5d16eaec'
down_revision: Union[str, None] = '8824f0acf3f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_weekly_plan_teacher_week', 'weekly_plans', type_='unique')
    op.create_unique_constraint('uq_weekly_plan_org_teacher_week', 'weekly_plans', ['organization_id', 'teacher_user_id', 'week_start_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_weekly_plan_org_teacher_week', 'weekly_plans', type_='unique')
    op.create_unique_constraint('uq_weekly_plan_teacher_week', 'weekly_plans', ['teacher_user_id', 'week_start_date'])
    # ### end Alembic commands ###
