"""add classes

Revision ID: 21a20e1a2625
Revises: 61bfa06e436d
Create Date: 2026-09-11 15:11:29.431539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '21a20e1a2625'
down_revision: Union[str, None] = '61bfa06e436d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('teacher_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('subject_name', sa.String(length=120), nullable=False),
    sa.Column('year_group', sa.Enum('NURSERY', 'RECEPTION', 'YEAR_1', 'YEAR_2', 'YEAR_3', 'YEAR_4', 'YEAR_5', 'YEAR_6', 'YEAR_7', 'YEAR_8', 'YEAR_9', 'YEAR_10', 'YEAR_11', 'YEAR_12', 'YEAR_13', name='year_group'), nullable=False),
    sa.Column('qualification', sa.String(length=100), nullable=True),
    sa.Column('exam_board_name', sa.String(length=120), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_organization_id'), 'classes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_classes_teacher_user_id'), 'classes', ['teacher_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_classes_teacher_user_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_organization_id'), table_name='classes')
    op.drop_table('classes')
    # ### end Alembic commands ###
