"""add class subject requirements for timetable auto-generation

Revision ID: 37d023080921
Revises: 7e247e663614
Create Date: 2026-09-16 17:55:50.718435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '37d023080921'
down_revision: Union[str, None] = '7e247e663614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_subject_requirements',
    sa.Column('timetable_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('periods_per_week', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timetable_id', 'class_id', 'subject_id', name='uq_class_subject_requirement')
    )
    op.create_index(op.f('ix_class_subject_requirements_timetable_id'), 'class_subject_requirements', ['timetable_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_class_subject_requirements_timetable_id'), table_name='class_subject_requirements')
    op.drop_table('class_subject_requirements')
    # ### end Alembic commands ###
