"""Add curriculum hierarchy

Revision ID: 46bfe59ea9bf
Revises: 21877c609ca3
Create Date: 2026-09-13 06:44:31.560925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '46bfe59ea9bf'
down_revision: Union[str, None] = '21877c609ca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curricula',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('key_stages',
    sa.Column('curriculum_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curricula.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curriculum_id', 'code', name='uq_key_stage_curriculum_code')
    )
    op.create_index(op.f('ix_key_stages_curriculum_id'), 'key_stages', ['curriculum_id'], unique=False)
    op.create_table('subjects',
    sa.Column('curriculum_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_id'], ['curricula.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curriculum_id', 'code', name='uq_subject_curriculum_code')
    )
    op.create_index(op.f('ix_subjects_curriculum_id'), 'subjects', ['curriculum_id'], unique=False)
    op.create_table('year_groups',
    sa.Column('key_stage_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['key_stage_id'], ['key_stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_stage_id', 'code', name='uq_year_group_key_stage_code')
    )
    op.create_index(op.f('ix_year_groups_key_stage_id'), 'year_groups', ['key_stage_id'], unique=False)
    op.create_table('programmes_of_study',
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('year_group_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['year_group_id'], ['year_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'year_group_id', name='uq_pos_subject_year_group')
    )
    op.create_index(op.f('ix_programmes_of_study_subject_id'), 'programmes_of_study', ['subject_id'], unique=False)
    op.create_index(op.f('ix_programmes_of_study_year_group_id'), 'programmes_of_study', ['year_group_id'], unique=False)
    op.create_table('curriculum_topics',
    sa.Column('programme_of_study_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['programme_of_study_id'], ['programmes_of_study.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curriculum_topics_programme_of_study_id'), 'curriculum_topics', ['programme_of_study_id'], unique=False)
    op.create_table('objectives',
    sa.Column('curriculum_topic_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['curriculum_topic_id'], ['curriculum_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('curriculum_topic_id', 'code', 'description', name='uq_objective_topic_code_description')
    )
    op.create_index(op.f('ix_objectives_curriculum_topic_id'), 'objectives', ['curriculum_topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_objectives_curriculum_topic_id'), table_name='objectives')
    op.drop_table('objectives')
    op.drop_index(op.f('ix_curriculum_topics_programme_of_study_id'), table_name='curriculum_topics')
    op.drop_table('curriculum_topics')
    op.drop_index(op.f('ix_programmes_of_study_year_group_id'), table_name='programmes_of_study')
    op.drop_index(op.f('ix_programmes_of_study_subject_id'), table_name='programmes_of_study')
    op.drop_table('programmes_of_study')
    op.drop_index(op.f('ix_year_groups_key_stage_id'), table_name='year_groups')
    op.drop_table('year_groups')
    op.drop_index(op.f('ix_subjects_curriculum_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_key_stages_curriculum_id'), table_name='key_stages')
    op.drop_table('key_stages')
    op.drop_table('curricula')
    # ### end Alembic commands ###
