"""Add substitution plans, timetable exceptions, and notifications

Revision ID: 64da61bf31c0
Revises: fa35d72e35d6
Create Date: 2026-09-13 07:54:42.098655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '64da61bf31c0'
down_revision: Union[str, None] = 'fa35d72e35d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('substitution_plans',
    sa.Column('teacher_absence_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'APPROVED', 'REJECTED', name='substitution_plan_status'), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teacher_absence_id'], ['teacher_absences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_absence_id', name='uq_substitution_plan_absence')
    )
    op.create_index(op.f('ix_substitution_plans_teacher_absence_id'), 'substitution_plans', ['teacher_absence_id'], unique=False)
    op.create_table('timetable_exceptions',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('timetable_entry_id', sa.UUID(), nullable=False),
    sa.Column('substitute_teacher_user_id', sa.UUID(), nullable=True),
    sa.Column('substitution_plan_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['substitute_teacher_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['substitution_plan_id'], ['substitution_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['timetable_entry_id'], ['timetable_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_exceptions_school_id'), 'timetable_exceptions', ['school_id'], unique=False)
    op.create_index(op.f('ix_timetable_exceptions_timetable_entry_id'), 'timetable_exceptions', ['timetable_entry_id'], unique=False)
    op.create_table('substitution_assignments',
    sa.Column('substitution_plan_id', sa.UUID(), nullable=False),
    sa.Column('affected_lesson_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'UNFILLED', name='substitution_assignment_status'), nullable=False),
    sa.Column('substitute_teacher_user_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['affected_lesson_id'], ['affected_lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['substitute_teacher_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['substitution_plan_id'], ['substitution_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('substitution_plan_id', 'affected_lesson_id', name='uq_assignment_plan_lesson')
    )
    op.create_index(op.f('ix_substitution_assignments_affected_lesson_id'), 'substitution_assignments', ['affected_lesson_id'], unique=False)
    op.create_index(op.f('ix_substitution_assignments_substitution_plan_id'), 'substitution_assignments', ['substitution_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_substitution_assignments_substitution_plan_id'), table_name='substitution_assignments')
    op.drop_index(op.f('ix_substitution_assignments_affected_lesson_id'), table_name='substitution_assignments')
    op.drop_table('substitution_assignments')
    op.drop_index(op.f('ix_timetable_exceptions_timetable_entry_id'), table_name='timetable_exceptions')
    op.drop_index(op.f('ix_timetable_exceptions_school_id'), table_name='timetable_exceptions')
    op.drop_table('timetable_exceptions')
    op.drop_index(op.f('ix_substitution_plans_teacher_absence_id'), table_name='substitution_plans')
    op.drop_table('substitution_plans')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
