"""add quick-generate worksheet homework translation and resource tagging

Revision ID: 7e247e663614
Revises: aabb6568b1bf
Create Date: 2026-09-15 16:15:06.416942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7e247e663614'
down_revision: Union[str, None] = 'aabb6568b1bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_plan_versions', sa.Column('worksheet_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('lesson_plan_versions', sa.Column('homework_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('lesson_plan_versions', sa.Column('translation_bn', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('lesson_plans', sa.Column('scheduled_date', sa.Date(), nullable=True))
    op.add_column('resources', sa.Column('subject_id', sa.UUID(), nullable=True))
    op.add_column('resources', sa.Column('year_group_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_resources_subject_id'), 'resources', ['subject_id'], unique=False)
    op.create_index(op.f('ix_resources_year_group_id'), 'resources', ['year_group_id'], unique=False)
    op.create_foreign_key(None, 'resources', 'year_groups', ['year_group_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'resources', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.drop_index(op.f('ix_resources_year_group_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_subject_id'), table_name='resources')
    op.drop_column('resources', 'year_group_id')
    op.drop_column('resources', 'subject_id')
    op.drop_column('lesson_plans', 'scheduled_date')
    op.drop_column('lesson_plan_versions', 'translation_bn')
    op.drop_column('lesson_plan_versions', 'homework_content')
    op.drop_column('lesson_plan_versions', 'worksheet_content')
    # ### end Alembic commands ###
