"""add worksheets and homework tables

Revision ID: 93f4e57e7bcf
Revises: 7d2f036122f8
Create Date: 2026-09-11 19:37:31.928585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '93f4e57e7bcf'
down_revision: Union[str, None] = '7d2f036122f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homework',
    sa.Column('lesson_plan_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_plan_id'], ['lesson_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homework_lesson_plan_id'), 'homework', ['lesson_plan_id'], unique=False)
    op.create_table('worksheets',
    sa.Column('lesson_plan_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_plan_id'], ['lesson_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worksheets_lesson_plan_id'), 'worksheets', ['lesson_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worksheets_lesson_plan_id'), table_name='worksheets')
    op.drop_table('worksheets')
    op.drop_index(op.f('ix_homework_lesson_plan_id'), table_name='homework')
    op.drop_table('homework')
    # ### end Alembic commands ###
