"""Add timetable core (academic years, rooms, time slots, timetables, entries, qualifications, availability)

Revision ID: a23ee962004f
Revises: be11ba01b226
Create Date: 2026-09-13 07:31:42.514689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a23ee962004f'
down_revision: Union[str, None] = 'be11ba01b226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_years_school_id'), 'academic_years', ['school_id'], unique=False)
    op.create_table('rooms',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_school_id'), 'rooms', ['school_id'], unique=False)
    op.create_table('teacher_subject_qualifications',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('teacher_user_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'teacher_user_id', 'subject_id', name='uq_teacher_subject_qualification')
    )
    op.create_index(op.f('ix_teacher_subject_qualifications_school_id'), 'teacher_subject_qualifications', ['school_id'], unique=False)
    op.create_index(op.f('ix_teacher_subject_qualifications_teacher_user_id'), 'teacher_subject_qualifications', ['teacher_user_id'], unique=False)
    op.create_table('time_slots',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'day_of_week', 'start_time', 'end_time', name='uq_time_slot')
    )
    op.create_index(op.f('ix_time_slots_school_id'), 'time_slots', ['school_id'], unique=False)
    op.create_table('teacher_availabilities',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('teacher_user_id', sa.UUID(), nullable=False),
    sa.Column('time_slot_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'UNAVAILABLE', name='teacher_availability_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'teacher_user_id', 'time_slot_id', name='uq_teacher_availability')
    )
    op.create_index(op.f('ix_teacher_availabilities_school_id'), 'teacher_availabilities', ['school_id'], unique=False)
    op.create_index(op.f('ix_teacher_availabilities_teacher_user_id'), 'teacher_availabilities', ['teacher_user_id'], unique=False)
    op.create_table('timetables',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('academic_year_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_year_id'], ['academic_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetables_school_id'), 'timetables', ['school_id'], unique=False)
    op.create_table('timetable_entries',
    sa.Column('timetable_id', sa.UUID(), nullable=False),
    sa.Column('time_slot_id', sa.UUID(), nullable=False),
    sa.Column('teacher_user_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('room_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['time_slot_id'], ['time_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_entries_teacher_user_id'), 'timetable_entries', ['teacher_user_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_time_slot_id'), 'timetable_entries', ['time_slot_id'], unique=False)
    op.create_index(op.f('ix_timetable_entries_timetable_id'), 'timetable_entries', ['timetable_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timetable_entries_timetable_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_time_slot_id'), table_name='timetable_entries')
    op.drop_index(op.f('ix_timetable_entries_teacher_user_id'), table_name='timetable_entries')
    op.drop_table('timetable_entries')
    op.drop_index(op.f('ix_timetables_school_id'), table_name='timetables')
    op.drop_table('timetables')
    op.drop_index(op.f('ix_teacher_availabilities_teacher_user_id'), table_name='teacher_availabilities')
    op.drop_index(op.f('ix_teacher_availabilities_school_id'), table_name='teacher_availabilities')
    op.drop_table('teacher_availabilities')
    op.drop_index(op.f('ix_time_slots_school_id'), table_name='time_slots')
    op.drop_table('time_slots')
    op.drop_index(op.f('ix_teacher_subject_qualifications_teacher_user_id'), table_name='teacher_subject_qualifications')
    op.drop_index(op.f('ix_teacher_subject_qualifications_school_id'), table_name='teacher_subject_qualifications')
    op.drop_table('teacher_subject_qualifications')
    op.drop_index(op.f('ix_rooms_school_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_academic_years_school_id'), table_name='academic_years')
    op.drop_table('academic_years')
    # ### end Alembic commands ###
