"""Add classes, tasks, and lesson plan school/class linkage

Revision ID: be11ba01b226
Revises: 06e9cafed403
Create Date: 2026-09-13 07:15:20.545703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'be11ba01b226'
down_revision: Union[str, None] = '06e9cafed403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('year_group_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['year_group_id'], ['year_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_owner_user_id'), 'classes', ['owner_user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to_user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='task_priority'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='task_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assigned_to_user_id'), 'tasks', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_tasks_school_id'), 'tasks', ['school_id'], unique=False)
    op.add_column('lesson_plans', sa.Column('school_id', sa.UUID(), nullable=True))
    op.add_column('lesson_plans', sa.Column('class_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_lesson_plans_school_id'), 'lesson_plans', ['school_id'], unique=False)
    op.create_foreign_key(None, 'lesson_plans', 'schools', ['school_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'lesson_plans', 'classes', ['class_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lesson_plans', type_='foreignkey')
    op.drop_constraint(None, 'lesson_plans', type_='foreignkey')
    op.drop_index(op.f('ix_lesson_plans_school_id'), table_name='lesson_plans')
    op.drop_column('lesson_plans', 'class_id')
    op.drop_column('lesson_plans', 'school_id')
    op.drop_index(op.f('ix_tasks_school_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to_user_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_classes_owner_user_id'), table_name='classes')
    op.drop_table('classes')
    # ### end Alembic commands ###
