"""add resources and resource_chunks

Revision ID: ee89fb1bcc42
Revises: f7b534dc8830
Create Date: 2026-09-11 15:47:03.756109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'ee89fb1bcc42'
down_revision: Union[str, None] = 'f7b534dc8830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('resource_type', sa.Enum('EXAM_SPECIFICATION', 'SCHEME_OF_WORK', 'TEACHER_NOTES', 'LESSON_RESOURCE', 'WORKSHEET', 'PAST_PAPER', 'MARK_SCHEME', 'PRACTICAL_GUIDE', 'CURRICULUM_DOCUMENT', 'OTHER', name='resource_type'), nullable=False),
    sa.Column('visibility', sa.Enum('PRIVATE', 'ORGANIZATION', name='resource_visibility'), nullable=False),
    sa.Column('subject_name', sa.String(length=120), nullable=True),
    sa.Column('exam_board_name', sa.String(length=120), nullable=True),
    sa.Column('qualification', sa.String(length=100), nullable=True),
    sa.Column('year_group', postgresql.ENUM('NURSERY', 'RECEPTION', 'YEAR_1', 'YEAR_2', 'YEAR_3', 'YEAR_4', 'YEAR_5', 'YEAR_6', 'YEAR_7', 'YEAR_8', 'YEAR_9', 'YEAR_10', 'YEAR_11', 'YEAR_12', 'YEAR_13', name='year_group', create_type=False), nullable=True),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('unit', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('extraction_status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='resource_extraction_status'), nullable=False),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_organization_id'), 'resources', ['organization_id'], unique=False)
    op.create_index(op.f('ix_resources_uploaded_by_user_id'), 'resources', ['uploaded_by_user_id'], unique=False)
    op.create_table('resource_chunks',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_chunks_resource_id'), 'resource_chunks', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_chunks_resource_id'), table_name='resource_chunks')
    op.drop_table('resource_chunks')
    op.drop_index(op.f('ix_resources_uploaded_by_user_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_organization_id'), table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
