"""Add resources table

Revision ID: f104d3b834f0
Revises: 46bfe59ea9bf
Create Date: 2026-09-13 06:50:38.892055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f104d3b834f0'
down_revision: Union[str, None] = '46bfe59ea9bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=150), nullable=False),
    sa.Column('kind', sa.Enum('PDF', 'DOCX', 'PPTX', 'IMAGE', 'TEXT', name='resource_kind'), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('extraction_status', sa.Enum('PENDING', 'DONE', 'FAILED', 'NOT_APPLICABLE', name='resource_extraction_status'), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extraction_error', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_owner_user_id'), 'resources', ['owner_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_owner_user_id'), table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
