"""add lesson plans and versions

Revision ID: f7b534dc8830
Revises: 21a20e1a2625
Create Date: 2026-09-11 15:20:03.271066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f7b534dc8830'
down_revision: Union[str, None] = '21a20e1a2625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_plans',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('teacher_user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('topic', sa.String(length=250), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('template_type', sa.Enum('STANDARD', 'PRACTICAL', 'REVISION', 'EXAM_PREP', 'NEW_TOPIC', 'RETRIEVAL', 'ASSESSMENT', 'REVIEW', 'DOUBLE', 'SHORT', name='lesson_plan_template_type'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='lesson_plan_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_plans_class_id'), 'lesson_plans', ['class_id'], unique=False)
    op.create_index(op.f('ix_lesson_plans_organization_id'), 'lesson_plans', ['organization_id'], unique=False)
    op.create_index(op.f('ix_lesson_plans_teacher_user_id'), 'lesson_plans', ['teacher_user_id'], unique=False)
    op.create_table('lesson_plan_versions',
    sa.Column('lesson_plan_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lesson_plan_id'], ['lesson_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_plan_id', 'version_number', name='uq_lesson_plan_version_number')
    )
    op.create_index(op.f('ix_lesson_plan_versions_lesson_plan_id'), 'lesson_plan_versions', ['lesson_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_plan_versions_lesson_plan_id'), table_name='lesson_plan_versions')
    op.drop_table('lesson_plan_versions')
    op.drop_index(op.f('ix_lesson_plans_teacher_user_id'), table_name='lesson_plans')
    op.drop_index(op.f('ix_lesson_plans_organization_id'), table_name='lesson_plans')
    op.drop_index(op.f('ix_lesson_plans_class_id'), table_name='lesson_plans')
    op.drop_table('lesson_plans')
    # ### end Alembic commands ###
