"""Add teacher absences and affected lessons

Revision ID: fa35d72e35d6
Revises: a23ee962004f
Create Date: 2026-09-13 07:43:45.750071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fa35d72e35d6'
down_revision: Union[str, None] = 'a23ee962004f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_absences',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('teacher_user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('reported_by_user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_absences_school_id'), 'teacher_absences', ['school_id'], unique=False)
    op.create_index(op.f('ix_teacher_absences_teacher_user_id'), 'teacher_absences', ['teacher_user_id'], unique=False)
    op.create_table('affected_lessons',
    sa.Column('teacher_absence_id', sa.UUID(), nullable=False),
    sa.Column('timetable_entry_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_absence_id'], ['teacher_absences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timetable_entry_id'], ['timetable_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affected_lessons_teacher_absence_id'), 'affected_lessons', ['teacher_absence_id'], unique=False)
    op.create_index(op.f('ix_affected_lessons_timetable_entry_id'), 'affected_lessons', ['timetable_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_affected_lessons_timetable_entry_id'), table_name='affected_lessons')
    op.drop_index(op.f('ix_affected_lessons_teacher_absence_id'), table_name='affected_lessons')
    op.drop_table('affected_lessons')
    op.drop_index(op.f('ix_teacher_absences_teacher_user_id'), table_name='teacher_absences')
    op.drop_index(op.f('ix_teacher_absences_school_id'), table_name='teacher_absences')
    op.drop_table('teacher_absences')
    # ### end Alembic commands ###
